# Generated by Django 3.2.7 on 2021-09-23 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vokabel_trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liste',
            options={'verbose_name_plural': 'Listen'},
        ),
        migrations.CreateModel(
            name='Vokabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deutsch', models.CharField(max_length=100)),
                ('franz', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vokabel_trainer.liste')),
            ],
            options={
                'verbose_name_plural': 'Vokabeln',
            },
        ),
    ]
