# Generated by Django 3.2.7 on 2021-09-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vokabel_trainer', '0002_auto_20210923_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vokabel',
            old_name='franz',
            new_name='franzoesisch',
        ),
    ]
