# Generated by Django 3.2.7 on 2021-09-24 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vokabel_trainer', '0004_abfrage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abfrage',
            name='vokabeln',
            field=models.ManyToManyField(limit_choices_to={'liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vokabel_trainer.liste')}, to='vokabel_trainer.Vokabel'),
        ),
    ]
