# Generated by Django 3.2.7 on 2021-09-24 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vokabel_trainer', '0005_alter_abfrage_vokabeln'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abfrage',
            name='vokabeln',
            field=models.ManyToManyField(limit_choices_to=models.Q(('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vokabel_trainer.liste'))), to='vokabel_trainer.Vokabel'),
        ),
    ]
