# Generated by Django 3.2.7 on 2021-09-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vokabel_trainer', '0007_auto_20210924_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abfrage',
            name='vokabeln',
            field=models.ManyToManyField(to='vokabel_trainer.Vokabel'),
        ),
    ]
