# Generated by Django 3.2.7 on 2021-09-24 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vokabel_trainer', '0008_alter_abfrage_vokabeln'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abfrage',
        ),
    ]
