# Generated by Django 3.2.7 on 2021-09-24 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vokabel_trainer', '0009_delete_abfrage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abfrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vokabel_trainer.liste')),
                ('vokabeln', models.ManyToManyField(to='vokabel_trainer.Vokabel')),
            ],
            options={
                'verbose_name_plural': 'Abfragen',
            },
        ),
    ]
