# Generated by Django 3.2.7 on 2021-09-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vokabel_trainer', '0011_abfrage_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='vokabel',
            name='abfragen',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vokabel',
            name='korrekt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
