# Generated by Django 3.2.7 on 2021-09-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vokabel_trainer', '0012_auto_20210925_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='vokabel',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='vokabel',
            name='abfragen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vokabel',
            name='korrekt',
            field=models.IntegerField(default=0),
        ),
    ]
