# Generated by Django 3.2.7 on 2021-09-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vokabel_trainer', '0013_auto_20210925_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='abfrage',
            name='reihenfolge',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
