# Generated by Django 3.2.7 on 2021-09-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vokabel_trainer', '0014_abfrage_reihenfolge'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
