# Generated by Django 3.2.7 on 2021-09-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vokabel_trainer', '0018_auto_20210926_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liste',
            name='file',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
