# Generated by Django 3.2.7 on 2021-09-26 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vokabel_trainer', '0020_alter_liste_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liste',
            name='file',
        ),
    ]
