# Generated by Django 3.2.7 on 2021-09-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vokabel_trainer', '0021_remove_liste_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
