# Generated by Django 3.2.7 on 2021-09-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vokabel_trainer', '0022_liste_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liste',
            old_name='beschreibung',
            new_name='name',
        ),
    ]
