# Generated by Django 3.2.7 on 2021-09-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vokabel_trainer', '0023_rename_beschreibung_liste_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='liste',
            name='beschreibung',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
