# Generated by Django 3.2.7 on 2021-10-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vokabel_trainer', '0024_liste_beschreibung'),
    ]

    operations = [
        migrations.AddField(
            model_name='abfrage',
            name='anzahl_abfragen',
            field=models.IntegerField(default=0),
        ),
    ]
