# Generated by Django 3.2.7 on 2021-10-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vokabel_trainer', '0025_abfrage_anzahl_abfragen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vokabel',
            name='stufe',
            field=models.IntegerField(default=0),
        ),
    ]
