# Generated by Django 3.2.7 on 2021-10-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vokabel_trainer', '0026_vokabel_stufe'),
    ]

    operations = [
        migrations.AddField(
            model_name='abfrage',
            name='wiederholungen',
            field=models.IntegerField(default=0),
        ),
    ]
